c_stdlib_version:          # [osx]
  - "12.3"                 # [osx]
MACOSX_SDK_VERSION:        # [osx]
  - "12.3"                 # [osx]
c_compiler:                # [win]
  - m2w64-gcc                 # [win]
cxx_compiler:              # [win]
  - m2w64-gcc                 # [win]
rust_compiler_version:
  - "1.89"
