[build]
rustflags = ["-C", "symbol-mangling-version=v0", "--cfg", "tokio_unstable"]
target-dir = "C:\\b"
jobs = 1

[profile.release]
# Reduce optimization level to save memory (was opt-level=3)
opt-level = 2
# Disable LTO to reduce memory usage (was enabled)
lto = false
# Increase codegen units to reduce per-unit memory (was codegen-units=1)
codegen-units = 4
# Reduce debug info to save memory
debug = 0

[registries.crates-io]
protocol = "sparse"

[net]
git-fetch-with-cli = true

[target.'cfg(target_os = "windows")']
rustflags = [
    "--cfg",
    "windows_slim_errors",        # This cfg will reduce the size of `windows::core::Error` from 16 bytes to 4 bytes
    "-C",
    "target-feature=+crt-static", # This fixes the linking issue when compiling livekit on Windows
    "-C",
    "link-arg=/NODEFAULTLIB:MSVCRTD", # Explicitly exclude debug runtime to avoid conflicts
]
