[build]
# Use environment variable for target dir to support temp directories
target-dir = "${CARGO_TARGET_DIR}"
# Force GNU target as default for MinGW compatibility
default-target = "x86_64-pc-windows-gnu"
target = "x86_64-pc-windows-gnu"

[net]
git-fetch-with-cli = true

[profile.release]
codegen-units = 4

[target.x86_64-pc-windows-gnu]
rustflags = [
    "--cfg",
    "windows_slim_errors",        # Reduce the size of windows::core::Error from 16 bytes to 4 bytes
    "-C",
    "target-feature=+crt-static", # Use static CRT linking for MinGW compatibility
]
