[target."cfg(all())"]
rustflags = []

[target."cfg(windows)"]
rustflags = []

[target.x86_64-pc-windows-msvc]
linker = "link.exe"
rustflags = []

[profile.release]
debug = false
strip = true
codegen-units = 1
lto = true
panic = "abort"

[build]
rustflags = []
