[build]
# Use environment variable for target dir to support temp directories
target-dir = "${CARGO_TARGET_DIR}"

[net]
git-fetch-with-cli = true

[profile.release]
# Standard release profile - following Zed's official Windows development guide
codegen-units = 4

[target.'cfg(target_os = "windows")']
rustflags = [
    "--cfg",
    "windows_slim_errors",        # Reduce the size of windows::core::Error from 16 bytes to 4 bytes
    "-C",
    "target-feature=+crt-static", # Use static CRT linking
]
